owner: greendiscord
repo:  apolgandricochetuptime


sites:
  - name: Main Site
    url: https://apolga.com
  - name: EU 1
    url: https://eu.apolga.com
  - name: NA 1
    url: https://na.apolga.com

status-website:
  cname: status.apolga.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Apolga Status
  introTitle: "**Apolga and Ricochet Revival Status**"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Apolga
      href: https://apolga.com


