owner: greendiscord
repo:  apolgandricochetuptime


sites:
  - name: Main Site
    url: https://apolga.com
  - name: EU 1
    url: https://$APOLGA_EU
  - name: NA 1
    url: https://$APOLGA_NA
  - name: Ricochet EU
    check: "tcp-ping"
    url: $RICOCHET_EU
    port: 27015
  - name: Ricochet NA
    check: "tcp-ping"
    url: $RICOCHET_NA
    port: 27015


assignees:
  - GreenDiscord


status-website:
  cname: status.apolga.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Apolga Status
  introTitle: "**Apolga and Ricochet Revival Status**"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Apolga
      href: https://apolga.com


